import img1 from "@/assets/favourites/image1.png";
import img2 from "@/assets/favourites/image2.png";
import img3 from "@/assets/favourites/image3.png";
import img4 from "@/assets/favourites/image4.png";
import img5 from "@/assets/favourites/image5.png";
import img6 from "@/assets/favourites/image6.png";
import img7 from "@/assets/favourites/image7.png";
import img8 from "@/assets/favourites/image8.png";
import img9 from "@/assets/favourites/image9.png";
import img10 from "@/assets/favourites/image10.png";
import avatarSmile from '../../assets/avatarSmile.png'
import avatarSpecs from '../../assets/avatarSpecs.png'
import avatarOoo from '../../assets/avatarOoo.png'

export const donateList = [
  {
    name: 'Karthik Raja',
    img: avatarSmile,
    bg: img1,
    title: "Lorem ipsum dolor sit amet elit sit amet elit sit",
    donations: '2474',
    amt: '2,500',
    total: '10,000',
    progress: 0,
    status: 'Verified',
    days: '2 days left',
    urgent: false,
  },
  {
    name: 'Raj Kumar',
    img: avatarSpecs,
    bg: img2,
    title: `Lorem ipsum dolor sit amet elit sit amet elit sit Lorem ipsum dolor sit amet elit sit amet elit sit `,
    donations: '4573',
    amt: '4,200',
    total: '9,000',
    progress: 0,
    status: 'Tax Benefits',
    days: '4 days left',
    urgent: false,
  },
  {
    name: 'Vimal Raj',
    img: avatarSpecs,
    bg: img3,
    title: "Lorem ipsum dolor sit amet elit sit amet elit sit",
    donations: '5134',
    amt: '43,445',
    total: '88,000',
    progress: 0,
    status: 'Tax Benefits',
    days: '2 days left',
    urgent: true,
  },
  {
    name: 'Rajesh kumar',
    img: avatarOoo,
    bg: img4,
    title: "Lorem ipsum dolor sit amet elit sit amet elit sit Lorem ipsum dolor sit amet elit sit amet elit sit",
    donations: '2921',
    amt: '4,200',
    total: '9,000',
    progress: 0,
    status: 'Verified',
    days: '3 days left',
    urgent: false,
  },
  {
    name: 'Ganesh Kanna',
    img: avatarSpecs,
    bg: img5,
    title: `Lorem ipsum dolor sit amet elit sit amet elit sit`,
    donations: '2962',
    amt: '2,230',
    total: '15,000',
    progress: 0,
    status: 'Verified',
    days: '1 days left',
    urgent: false,
  },
  {
    name: 'Jai Kishan',
    img: avatarSmile,
    bg: img6,
    title: "Lorem ipsum dolor sit amet elit sit amet elit sit",
    donations: '7432',
    amt: '12,254',
    total: '20,000',
    progress: 0,
    status: 'Tax Benefits',
    days: '5 days left',
    urgent: true,
  },
  {
    name: 'Kishore Kumar',
    img: avatarSpecs,
    bg: img7,
    title: "Lorem ipsum dolor sit amet elit sit amet elit sit Lorem ipsum dolor sit amet elit sit amet elit sit",
    donations: '1864',
    amt: '2,230',
    total: '90,000',
    progress: 0,
    status: 'Verified',
    days: '2 days left',
    urgent: false,
  },
  {
    name: 'Praveen Raj',
    img: avatarSpecs,
    bg: img8,
    title: "Lorem ipsum dolor sit amet elit sit amet elit sit Lorem ipsum dolor sit amet elit sit amet elit sit",
    donations: '9543',
    amt: '1,530',
    total: '5,000',
    progress: 0,
    status: 'Tax Benefits',
    days: '3 days left',
    urgent: false,
  },
  {
    name: 'Mohammed Ali',
    img: avatarOoo,
    bg: img9,
    title: "Lorem ipsum dolor sit amet elit sit amet elit sit Lorem ipsum dolor sit amet elit sit amet elit sit",
    donations: '4765',
    amt: '6,230',
    total: '10,500',
    progress: 0,
    status: 'Tax Benefits',
    days: '1 days left',
    urgent: false,
  },
  {
    name: 'Zakir Hussain',
    img: avatarSmile,
    bg: img10,
    title: "Lorem ipsum dolor sit amet elit sit amet elit sit",
    donations: '3451',
    amt: '5,230',
    total: '12,000',
    progress: 0,
    status: 'Tax Benefits',
    days: '4 days left',
    urgent: false,
  },
];
